### PR TITLE
tweak: remove cid column

### PR DESCRIPTION
**Pull request by Waves966**
## Description

It doesn't fix an issue but removed an unused column from the database.

## Checklist

I didn't load the server setter shit because im lazy.

- [x ] I have personally loaded this code into an updated qbcore project and checked all of its functionality.
- [ x] My code fits the style guidelines.
- [ x] My PR fits the contribution guidelines.

### CODE REVIEW

**Comment by JericoFX** [comment]
cid is use for the multicharacter, cid is actually the amount of characters you have, works like the position of the caracter 1,2,3...
https://github.com/QBCore-Remastered/qb-multicharacter/blob/main/server/main.lua#L103
https://github.com/QBCore-Remastered/qb-multicharacter/blob/main/html/index.html#L61

**Comment by Waves966** [comment]
Please view my qb-multicharacter PR which removes the new for the CID
column in multicharacter as well.

**Comment by JericoFX** [comment]
im sorry now i understand what you want to achive, you move the cid inside the character

**Comment by Waves966** [comment]
> 

Well not exactly. the cid is **already** in the charinfo is has since qbcore used steam

**Comment by Manason** [comment]
> > 
> 
> Well not exactly. the cid is **already** in the charinfo is has since qbcore used steam

You are saying the player.cid field isn't actually being used? I would think we should prefer descriptive columns over JSON columns to have a stronger data model.

**Comment by Waves966** [comment]
The whole player data needs to be reworked but that's not gonna happen so
here we are

**Pull request merged**
